
using System;
using Tib.Api.Financial;
using Tib.Api.Common;

namespace Tib.Api.Model.Merchant
{
    /// <summary>
    /// Represents the SaveMerchantAccountInfoArgs model.
    /// </summary>
    public class SaveMerchantAccountInfoArgs : ClientCallBaseArgs
    {
        
    /// <summary>
    /// The unique identifier of the merchant initiating the payment request.
    /// </summary>
    /// <value>Must be a valid GUID representing a registered merchant; cannot be empty or null.</value>
    public Guid MerchantId { get; set; }

    /// <summary>
    /// The target bank account for the direct payment.
    /// </summary>
    /// <value>Must be a valid, active AccountModel (e.g., accountNumber, routingNumber) belonging to the payer; cannot be null.</value>
    public AccountModel Account { get; set; }

    /// <summary>
    /// The one‑time two‑factor authentication code required to authorize the SaveMerchantAccountInfo request.
    /// </summary>
    /// <value>String containing the OTP (typically 6‑8 numeric characters). Required only when two‑factor authentication is enabled for the merchant. Must be valid for the current session and match the code generated by the merchant's authenticator; otherwise the request is rejected.</value>
    public string TwoFactorCode { get; set; }

    /// <summary>
    /// The answer to the merchant's configured two‑factor authentication security question.
    /// </summary>
    /// <value>String, required; must exactly match the stored answer (case‑sensitive); trimmed of leading/trailing whitespace; maximum length 255 characters.</value>
    public string TwoFactorSecurityAnswer { get; set; }

    }
}