
using System;
using static Tib.Api.Model.Enum;
using Tib.Api.Common;

namespace Tib.Api.Model.Payment
{
    /// <summary>
    /// Object that represent Bill to be paid by an End User
    /// </summary>
    public class CreatePaymentResponse : ClientBaseResponse
    {
        
    /// <summary>
    /// Retrieves or assigns the unique identifier for a payment.
    /// </summary>
    /// <value>Represents the unique identifier associated with a specific payment transaction.</value>
    public Guid? PaymentId { get; set; }

    /// <summary>
    /// Represents the payment flow automatically chosen when a request is set to AutoSelect mode.
    /// </summary>
    /// <value>Indicates that the system will determine the appropriate payment flow based on merchant settings and available methods without explicit client direction.</value>
    public PaymentFlowEnum? AutoSelectPaymentFlowResult { get; set; }

    /// <summary>
    /// Indicates the outcome of the payment flow parsing operation.
    /// </summary>
    /// <value>Enumeration that represents the result of interpreting the selected payment flow type, such as AutoSelect, Anonymous, DirectDeposit, DirectInterac, etc.</value>
    public PaymentFlowParsingResultEnum PaymentFlowParsingResult { get; set; }

    /// <summary>
    /// Represents the URL that directs the customer to the payment gateway for completing the transaction.
    /// </summary>
    /// <value>A string containing a fully qualified HTTPS link to the TIB Finance payment page. The link is generated by the API when a payment is created.</value>
    public string PaymentLink { get; set; }

    }
}